### ISSUE TITLE
Potential incompatibility with tensorflow==0.12.0rc0

### ISSUE THREAD

**Issue by bwall** [tkipf/gcn#1]
When I run train.py with tensorflow==0.12.0rc0, I get the following:
```
$ python train.py 
Traceback (most recent call last):
  File "train.py", line 59, in <module>
    model = model_func(placeholders, input_dim=features[2][1], logging=True)
  File "build/bdist.linux-x86_64/egg/gcn/models.py", line 147, in __init__
    self.build()
  File "build/bdist.linux-x86_64/egg/gcn/models.py", line 49, in build
    hidden = layer(self.activations[-1])
  File "build/bdist.linux-x86_64/egg/gcn/layers.py", line 75, in __call__
    outputs = self._call(inputs)
  File "build/bdist.linux-x86_64/egg/gcn/layers.py", line 168, in _call
    x = sparse_dropout(x, 1-self.dropout, self.num_features_nonzero)
  File "build/bdist.linux-x86_64/egg/gcn/layers.py", line 27, in sparse_dropout
    return pre_out * tf.inv(keep_prob)
AttributeError: 'module' object has no attribute 'inv'
```

Is there a known working version of TF I can install for testing this out?

**Comment by tkipf** [comment]
Hi bwall,

Thanks for reporting! This indeed seems to be an issue with the new TensorFlow version - I have just pushed a commit which should fix this (replaced tf.inf). Haven't yet upgraded to v0.12 yet, but I'll test later. Let me know when you run in any other difficulties. Thanks!

**Comment by bwall** [comment]
That did the trick, thank you :)
