### ISSUE TITLE
ImportError: No module named 'gcn'

### ISSUE THREAD

**Issue by liunianxuxie** [tkipf/gcn#124]
ImportError: No module named 'gcn'

**Comment by yunchengwang** [comment]
you need to run the setup.py first

**Comment by liunianxuxie** [comment]
Thanks

**Comment by atheeraa** [comment]
I ran setup.py first, but I still got the error : 

Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from gcn.utils import *
ModuleNotFoundError: No module named 'gcn'

can anyone please help?

**Comment by ConorKrystad** [comment]
I am having the same issue as atheeraa

**Comment by Shubydoobiedoo** [comment]
I am getting the same error as above.

I ran setup.py first, but I still got the error :

Traceback (most recent call last):
File "train.py", line 7, in
from gcn.utils import *
ModuleNotFoundError: No module named 'gcn'
