### ISSUE TITLE
Demo Error

### ISSUE THREAD

**Issue by karmeze** [tkipf/gcn#8]
Hi,

So I am trying to run the test dataset. I downloaded the original citeseer data, and I am still getting the same error below when running the command: python train.py --dataset citeseer

Traceback (most recent call last):
  File "train.py", line 59, in <module>
    model = model_func(placeholders, input_dim=features[2][1], logging=True)
  File "build/bdist.linux-x86_64/egg/gcn/models.py", line 144, in __init__
    self.build()
  File "build/bdist.linux-x86_64/egg/gcn/models.py", line 41, in build
    self._build()
  File "build/bdist.linux-x86_64/egg/gcn/models.py", line 167, in _build
    logging=self.logging))
  File "build/bdist.linux-x86_64/egg/gcn/layers.py", line 161, in __init__
    self._log_vars()
  File "build/bdist.linux-x86_64/egg/gcn/layers.py", line 82, in _log_vars
    tf.summary.histogram(self.name + '/vars/' + var, self.vars[var])
AttributeError: 'module' object has no attribute 'summary'

Thanks!

**Comment by tkipf** [comment]
Thanks for reporting your issue. This problem is related to an old version of TensorFlow. Can you upgrade to version 0.12 or 1.0 and try again?

**Comment by karmeze** [comment]
Alright so I upgraded from 0.9 to 1.0, errors surrounding labels. 

usr/local/lib/python2.7/dist-packages/gcn-1.0-py2.7.egg/gcn/utils.py:97: RuntimeWarning: divide by zero encountered in power
Traceback (most recent call last):
  File "train.py", line 59, in <module>
    model = model_func(placeholders, input_dim=features[2][1], logging=True)
  File "build/bdist.linux-x86_64/egg/gcn/models.py", line 144, in __init__
    self.build()
  File "build/bdist.linux-x86_64/egg/gcn/models.py", line 55, in build
    self._loss()
  File "build/bdist.linux-x86_64/egg/gcn/models.py", line 153, in _loss
    self.placeholders['labels_mask'])
  File "build/bdist.linux-x86_64/egg/gcn/metrics.py", line 6, in masked_softmax_cross_entropy
    loss = tf.nn.softmax_cross_entropy_with_logits(preds, labels)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1578, in softmax_cross_entropy_with_logits
    labels, logits)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1533, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

**Comment by tkipf** [comment]
Ok, looks like there are still compatibility issues with TensorFlow 1.0. I'll look into it. In the meantime you can use TensorFlow v0.12. Thanks for reporting!

**Comment by tkipf** [comment]
I checked again and this issue was fixed in https://github.com/tkipf/gcn/commit/193c0992007610b8ff65f3d3f5d6c418b13a343b . Please pull and re-run `python setup.py install`.

**Comment by karmeze** [comment]
Ok great thank you so much!

Karleigh Mezeivtch

Lieber Institute for Brain Development
Johns Hopkins Medical Campus
855 North Wolfe Street, Suite 300
Baltimore, MD 21205
karleigh.mezeivtch@libd.org

________________________________
